server.port=8080
spring.application.name=HuffZip

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=120MB

spring.web.resources.static-locations=classpath:/static/
logging.level.com.huffzip=INFO
